name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: abystoma/external-workflow
          ref: branch
      - name: Greetings
        run: echo "$(<greetings.txt)"
